### ISSUE TITLE
what do i have to put into the <YOUR_GRAPHITE_PREFIX>?

### ISSUE THREAD

**Issue by fitzfuchs** [Crapworks/check_ceph_dash#2]
Hi, what do i have to put into the <YOUR_GRAPHITE_PREFIX>?
The URL of my graphite server, the folder /var/lib/grafana or something else?

greetings
fitzfuchs

**Comment by Crapworks** [comment]
Hi,
in grafana, you define your data sources separate from the dashboard. <YOUR_GRAPHITE_PREFIX> means everything that is in your graphite path preceding the output of `check_ceph_dash`.

For example, if you have a graphite metric called

```
monitoring.cephmon01.read_bytes_sec.value
```

<YOUR_GRAPHITE_PREFIX> has to be replaces with `monitoring.cephmon01`

Regards,
Christian
