### ISSUE TITLE
prepare for luminous existence WARNING:

### ISSUE THREAD

**Issue by wzs803** [Crapworks/check_ceph_dash#4]
![image](https://user-images.githubusercontent.com/3351066/30859897-f880eaa4-a2f7-11e7-8570-bea16111b6f7.png)

**Comment by Crapworks** [comment]
Although I can only guess what this issue is supposed to mean, I do use now the ```status``` field instead of the ```overall_status``` field to evaluate the state of the check. Can you please check the current version and tell me if this works now for you?

**Comment by lmaneos** [comment]
`get_exit_code()` still uses `overall_status` unconditionally.   This makes the exit status `1` (aka WARNING) when checking a Luminous host.   I have no idea why `overall_status` reports `HEALTH_WARN` while status is `HEALTH_OK` though.

**Comment by k0ste** [comment]
@wzs803, @lmaneos check #5.

**Comment by Crapworks** [comment]
This should be fixed by #5, feel free to reopen if you still encounter errors.
